### ISSUE TITLE
Sankey diagram order can't be specified

### ISSUE THREAD

**Issue by jarben** [apache/echarts#4986]
Version: 3.4.0

I'm struggling to find out how to manage order of nodes in the sankey diagram. For example, this diagram: 

![image](https://cloud.githubusercontent.com/assets/561365/22152521/a4d462de-df23-11e6-89cf-1afe9cbc1dc7.png)

is defined (source attached [sankey-order.zip](https://github.com/ecomfe/echarts/files/719575/sankey-order.zip)) in this order: 

nodes: 
1. Financial Services 
2. Energy & Utilities
3. Mobility Transportation

1. Germany
2. Italy
3. Netherlands

links: 
1. Financial Services -> Germany
2. Financial Services -> Italy
3. Financial Services - Netherlands
...

where the order on the diagram is: 
1. Mobility Transportation
2. Financial Services 
3. Energy & Utilities

1. Germany
2. Netherlands
3. Italy

Which doesn't reflect the source code. Is there any way to do this - provide some sort of order index or simply order by given order? 

Thanks for any suggestion!

**Comment by jarben** [comment]
It seems like the order is based on values, I've changed all values to "1" and now it shows as: 
![image](https://cloud.githubusercontent.com/assets/561365/22153832/3c011508-df29-11e6-8dbf-01157764bc37.png)

Is there any way to change ordering, say by order in the source file or provided sortFn?

**Comment by jarben** [comment]
Any update on this?

**Comment by iandvt** [comment]
+1 - Another option could be allowing layoutIterations to be set to 0. Allowing the user to sort the nodes

**Comment by JamieChung** [comment]
+1 Would love more control on how to change the ordering of the nodes.

**Comment by shyamsdmx** [comment]
+1 Any update on the issue ?

**Comment by deqingli** [comment]
Hi everyone，I will follow this issue, sorry for letting you wait so long!

**Comment by deqingli** [comment]
Hi everyone,  I have fixed this problem, which will be released next version.  Now nodes sort by the order in series.data.  Thanks for your suggestions!

**Comment by deqingli** [comment]
If there any problem please reopen this issue.

**Comment by ericksepulveda** [comment]
any updates about how to do this in 2019?

**Comment by jbadilla** [comment]
Hey deqingli,

"Now nodes sort by the order in series.data and will not be changed even your resize the diagram"

I think this is not true. I have reordered my data array to fit the order I want and it still does not work.

@iandvt What is this solution with `layoutIterations`?

**Comment by pvictor** [comment]
@jbadilla you can use `layoutIterations: 0` to disable it, and apparently order is preserved.

**Comment by deqingli** [comment]
> Hey @deqingli ,
> 
> "Now nodes sort by the order in series.data and will not be changed even your resize the diagram"
> 
> I think this is not true. I have reordered my data array to fit the order I want and it still does not work.
> 
> @iandvt What is this solution with `layoutIterations`? Anyway to disable this?

Hi @jbadilla, If you want the node ordered by the `series.data`, you can set `layoutIterations: 0`.
